name: Send a newsletter.

on:
  schedule:
    # every hour.
    - cron: "*/5 * * * *"

  repository_dispatch:
    types: manual-trigger

jobs:
  newsletter:
    name: newsletter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1        

      - name: Decrypt .env.gpg => .env
        env:
          SYMMETRIC_KEY: ${{ secrets.GPG_KEY }}
        run: gpg --quiet --batch --yes --decrypt --passphrase="$SYMMETRIC_KEY" --output=.env .env.gpg

      - name: Install dependencies
        run: pipenv install

      - name: Get current date
        id: current_date
        run: echo "::set-output UNTIL=date::$(date +'%Y-%m-%d')"
      
      - name: Get past 7 date
        id: past_date
        run: echo "::set-output SINCE=$(date -d \"$date -7 days\" +"%Y-%m-%d")"

      - name: Run the process
        run: 
          export $(cat .env | xargs) && pipenv run python main.py --since ${{ steps.past_date.output.SINCE }} --until ${{ steps.current_date.output.UNTIL }}
          
      - name: Encrypt .env => .env.gpg
        env:
          SYMMETRIC_KEY: ${{ secrets.GPG_KEY }}
        run: echo "$SYMMETRIC_KEY" | gpg --symmetric --batch --passphrase-fd 0 .env

      - name: Push .env.gpg
        run: |
          git commit -am 'Updating .env.gpg'
          git push
