name: Send a newsletter.

on:
  schedule:
    # every hour.
    - cron: "*/5 * * * *"

  repository_dispatch:
    types: manual-trigger

jobs:
  newsletter:
    name: newsletter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Decrypt .env.gpg => .env
        env:
          SYMMETRIC_KEY: ${{ secrets.GPG_KEY }}
        run: gpg --quiet --batch --yes --decrypt --passphrase="$SYMMETRIC_KEY" --output=.env .env.gpg

      - name: Run the process
        run: |
          UNTIL=$(echo date +%Y-%m-%d)
          SINCE=$(date -d "$date -7 days" +"%Y-%m-%d")
          SINCE="echo ${SINCE}"
          export $(cat .env | xargs) && pipenv run python main.py --since $SINCE --until $UNTIL
          
      - name: Encrypt .env => .env.gpg
        env:
          SYMMETRIC_KEY: ${{ secrets.GPG_KEY }}
        run: echo "$SYMMETRIC_KEY" | gpg --symmetric --batch --passphrase-fd 0 .env

      - name: Push .env.gpg
        run: |
          git commit -am 'Updating .env.gpg'
          git push
